CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documentoIdentificacion" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "apellido" varchar NOT NULL,
  "contrasena" varchar NOT NULL
);

CREATE TABLE "rol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL
);

CREATE TABLE "usuarioRol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idUsuario" integer NOT NULL,
  "idRol" integer NOT NULL,
  FOREIGN KEY ("idUsuario") REFERENCES "usuario"("id"),
  FOREIGN KEY ("idRol") REFERENCES "rol"("id")
);

CREATE TABLE "vehiculo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idUsuario" integer NOT NULL,
  "idTipoVehiculo" integer NOT NULL,
  "placa" varchar NOT NULL,
  FOREIGN KEY ("idUsuario") REFERENCES "usuario"("id"),
  FOREIGN KEY ("idTipoVehiculo") REFERENCES "tipoVehiculo"("id")
);

CREATE TABLE "tipoVehiculo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "tarifa" decimal(10,2) NOT NULL
);

CREATE TABLE "parqueadero" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idVehiculo" integer UNIQUE,
  "ubicacion" varchar NOT NULL,
  "disponibilidad" bool,
  FOREIGN KEY ("idVehiculo") REFERENCES "vehiculo"("id")
);

CREATE TABLE "reserva" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idParqueadero" integer NOT NULL,
  "idVehiculo" integer NOT NULL,
  "horaEntrada" timestamp NOT NULL,
  "estado" varchar,
  FOREIGN KEY ("idParqueadero") REFERENCES "parqueadero"("id"),
  FOREIGN KEY ("idVehiculo") REFERENCES "vehiculo"("id")
);

CREATE TABLE "tiquete" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idVehiculo" integer NOT NULL,
  "horaEntrada" timestamp NOT NULL,
  "horaSalida" timestamp,
  "descuento" decimal(10,2),
  "valor" decimal(10,2),
  FOREIGN KEY ("idVehiculo") REFERENCES "vehiculo"("id")
);

CREATE TABLE "factura" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor" decimal(10,2) NOT NULL
);

INSERT INTO "usuario" ("documento_identificacion", "nombre", "apellido", "contrasena")
VALUES ('1234567890', 'Juan', 'Pérez', 'contraseña123'),
('9876543210', 'Victor', 'Estupinan', 'contraseña321');

INSERT INTO "tipo_vehiculo" ("nombre", "tarifa")
VALUES ('Automóvil', 4000),
('Moto', 2000);

INSERT INTO "vehiculo" ("id_usuario", "id_tipo_vehiculo", "placa")
VALUES (1, 1, 'ABC123'),
(1, 2, 'ABC321'),
(2, 1, 'CBA123'),
(2, 2, 'CBA321');

INSERT INTO "parqueadero" ("id_vehiculo", "ubicacion", "disponibilidad")
VALUES (null, 'Piso 1, Espacio 01', true),
(null, 'Piso 1, Espacio 02', true)
(null, 'Piso 1, Espacio 03', true);